# Generated by Django 5.2.1 on 2025-11-05 13:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unique généré automatiquement. Utilisé dans headers Authorization.', unique=True, verbose_name='Clé API')),
                ('name', models.CharField(help_text="Description de la clé (ex. 'Projet camarade Jean', 'Test dev')", max_length=255, verbose_name='Nom descriptif')),
                ('is_active', models.BooleanField(default=True, help_text='Si désactivée, requêtes avec cette clé sont rejetées (401).', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_used', models.DateTimeField(blank=True, help_text='Timestamp dernière requête valide avec cette clé. Mise à jour par middleware.', null=True, verbose_name='Dernière utilisation')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text="Compteur incrémenté à chaque requête valide. Permet de tracker quel projet utilise le plus l'API.", verbose_name="Nombre d'utilisations")),
            ],
            options={
                'verbose_name': 'Clé API',
                'verbose_name_plural': 'Clés API',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-usage_count'], name='core_apikey_usage_c_861e21_idx')],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords_latitude', models.FloatField(help_text='Latitude décimale du point (ex. 3.8547). Validée entre -90 et 90.', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Latitude')),
                ('coords_longitude', models.FloatField(help_text='Longitude décimale du point (ex. 11.5021). Validée entre -180 et 180.', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Longitude')),
                ('label', models.CharField(db_index=True, help_text="Nom du point d'intérêt connu des taxis (ex. 'Carrefour Ekounou'). Obtenu via Mapbox Search API.", max_length=255, verbose_name='Nom du POI')),
                ('ville', models.CharField(blank=True, db_index=True, help_text="Ville du point (ex. 'Yaoundé'). Utilisé pour filtrage queries.", max_length=100, null=True, verbose_name='Ville')),
                ('quartier', models.CharField(blank=True, db_index=True, help_text="Quartier/sous-quartier (ex. 'Ngoa-Ekelle'). CRITIQUE pour filtrage similarité avant calculs Mapbox.", max_length=100, null=True, verbose_name='Quartier')),
                ('arrondissement', models.CharField(blank=True, help_text="Commune (ex. 'Yaoundé II'). Extrait de 'context' Mapbox Geocoding.", max_length=100, null=True, verbose_name='Arrondissement/Commune')),
                ('departement', models.CharField(blank=True, help_text="Département (ex. 'Mfoundi' pour Yaoundé). Fallback filtrage si quartier manque.", max_length=100, null=True, verbose_name='Département')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': "Point d'Intérêt",
                'verbose_name_plural': "Points d'Intérêt",
                'ordering': ['ville', 'quartier', 'label'],
                'indexes': [models.Index(fields=['ville', 'quartier'], name='core_point_ville_4571a0_idx'), models.Index(fields=['coords_latitude', 'coords_longitude'], name='core_point_coords__47b69b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance routière via Mapbox Directions API (driving-traffic). Inclut détours réels.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Distance (mètres)')),
                ('prix', models.FloatField(help_text='Prix réel payé par utilisateur en Francs CFA. Donnée cruciale pour estimations communautaires.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Prix payé (CFA)')),
                ('heure', models.CharField(blank=True, choices=[('matin', 'Matin (6h-12h)'), ('apres-midi', 'Après-midi (12h-18h)'), ('soir', 'Soir (18h-22h)'), ('nuit', 'Nuit (22h-6h)')], help_text="Heure du trajet. Si null, déduire via datetime.now() au moment de l'ajout.", max_length=20, null=True, verbose_name='Tranche horaire')),
                ('meteo', models.IntegerField(blank=True, help_text='0=Soleil, 1=Pluie légère, 2=Pluie forte, 3=Orage. Si null, appeler OpenMeteo API.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)], verbose_name='Code météo')),
                ('type_zone', models.IntegerField(blank=True, help_text='0=Urbaine, 1=Mixte, 2=Rurale. Si null, déduire via classes routes Mapbox (primary=urbaine).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Type de zone')),
                ('congestion_user', models.IntegerField(blank=True, help_text='Niveau embouteillages selon user (1=fluide, 10=bloqué). Complète Mapbox pour zones non couvertes.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Congestion utilisateur (1-10)')),
                ('congestion_moyen', models.FloatField(blank=True, help_text="Moyenne congestion segments Mapbox. Null si 'unknown' pour tous segments (fréquent Cameroun).", null=True, verbose_name='Congestion Mapbox (0-100)')),
                ('sinuosite_indice', models.FloatField(blank=True, help_text='Ratio distance/ligne droite ou force virages (°/km). 1.0=droit, >1.5=sinueux. Null si calcul échoue.', null=True, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Indice de sinuosité')),
                ('route_classe_dominante', models.CharField(blank=True, db_index=True, help_text="'primary', 'secondary', 'tertiary', etc. via Mapbox Streets v8. Null si indisponible.", max_length=50, null=True, verbose_name='Classe route dominante')),
                ('nb_virages', models.IntegerField(blank=True, help_text="Nombre maneuvers type 'turn'/'rotary' dans itinéraire Mapbox.", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de virages')),
                ('force_virages', models.FloatField(blank=True, help_text='Somme |bearing_before - bearing_after| / distance_km. Mesure complexité itinéraire.', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Force virages (°/km)')),
                ('duree_estimee', models.FloatField(blank=True, help_text='Durée via Mapbox avec trafic. Pour info uniquement.', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Durée estimée (secondes)')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, help_text='Timestamp ajout trajet par utilisateur.', verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_arrivee', models.ForeignKey(help_text="POI d'arrivée du trajet (ex. 'Carrefour Ekounou')", on_delete=django.db.models.deletion.CASCADE, related_name='trajets_arrivee', to='core.point', verbose_name="Point d'arrivée")),
                ('point_depart', models.ForeignKey(help_text="POI de départ du trajet (ex. 'Polytechnique Yaoundé')", on_delete=django.db.models.deletion.CASCADE, related_name='trajets_depart', to='core.point', verbose_name='Point de départ')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
                'ordering': ['-date_ajout'],
                'indexes': [models.Index(fields=['point_depart', 'point_arrivee'], name='core_trajet_point_d_ae8f74_idx'), models.Index(fields=['heure', 'meteo', 'type_zone'], name='core_trajet_heure_7446f8_idx'), models.Index(fields=['route_classe_dominante'], name='core_trajet_route_c_c0d885_idx')],
            },
        ),
    ]
