# Generated by Django 5.2.1 on 2025-12-11 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='qualite_trajet',
            field=models.IntegerField(default=5, help_text='Évaluation utilisateur de la difficulté du trajet (1=très facile/fluide, 10=très difficile/embouteillages/nids de poule). Valeur par défaut: 5 (normal). Paramètre culturel utilisé pour ML futur.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Qualité/Difficulté du trajet (1-10)'),
        ),
    ]
