# Generated by Django 5.2.1 on 2025-12-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trajet_qualite_trajet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('image_url', models.URLField(max_length=500, verbose_name="URL de l'image")),
                ('app_link', models.URLField(blank=True, max_length=500, null=True, verbose_name="Lien de l'application")),
                ('category', models.CharField(default='Transport', max_length=100, verbose_name='Catégorie')),
                ('color', models.CharField(default='#f3cd08', max_length=7, verbose_name='Couleur (HEX)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
                'ordering': ['-created_at'],
            },
        ),
    ]
