# Generated by Django 5.2.1 on 2025-12-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publicite'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicite',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='publicite',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre (EN)'),
        ),
    ]
