# Generated by Django 5.2.1 on 2026-01-01 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publicite_description_en_publicite_title_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du service client')),
                ('whatsapp', models.CharField(blank=True, help_text='Format international (ex: +237XXXXXXXXX)', max_length=20, null=True, verbose_name='Numéro WhatsApp')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse physique')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Page Facebook')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Compte Twitter/X')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Compte Instagram')),
                ('horaires', models.CharField(blank=True, help_text='Ex: Lun-Ven 8h-18h', max_length=100, null=True, verbose_name='Horaires de disponibilité')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informations de Contact',
                'verbose_name_plural': 'Informations de Contact',
            },
        ),
        migrations.CreateModel(
            name='OffreAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'offre")),
                ('duree_mois', models.PositiveIntegerField(help_text="Durée de l'abonnement en mois", verbose_name='Durée (mois)')),
                ('prix', models.DecimalField(decimal_places=0, help_text="Prix de l'abonnement en Francs CFA", max_digits=10, verbose_name='Prix (CFA)')),
                ('description', models.TextField(help_text="Description détaillée de l'offre et ses avantages", verbose_name='Description/Avantages')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage sur la page pricing (0=premier)", verbose_name="Ordre d'affichage")),
                ('is_popular', models.BooleanField(default=False, help_text="Met en valeur cette offre (badge 'Populaire')", verbose_name='Offre populaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Offre d'Abonnement",
                'verbose_name_plural': "Offres d'Abonnement",
                'ordering': ['ordre_affichage', 'prix'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMarketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom du service')),
                ('nom_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom (EN)')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('image_url', models.URLField(max_length=500, verbose_name="URL de l'image")),
                ('lien_redirection', models.URLField(help_text='URL vers le service (app store, site web, etc.)', max_length=500, verbose_name='Lien de redirection')),
                ('icone', models.CharField(default='Zap', help_text="Nom de l'icône Lucide (ex: Zap, Car, MapPin)", max_length=50, verbose_name='Icône')),
                ('couleur', models.CharField(default='#f3cd08', max_length=7, verbose_name='Couleur (HEX)')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_featured', models.BooleanField(default=False, help_text='Afficher en priorité dans les suggestions', verbose_name='Mis en avant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Marketplace',
                'verbose_name_plural': 'Services Marketplace',
                'ordering': ['ordre_affichage', '-is_featured', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='publicite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Publicité (Service Partenaire)', 'verbose_name_plural': 'Publicités (Services Partenaires)'},
        ),
        migrations.AddField(
            model_name='publicite',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email du gestionnaire de cette publicité', max_length=254, null=True, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='publicite',
            name='contact_telephone',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp/téléphone du gestionnaire', max_length=20, null=True, verbose_name='Téléphone de contact'),
        ),
        migrations.AddField(
            model_name='publicite',
            name='nom_entreprise',
            field=models.CharField(blank=True, help_text="Nom de l'entreprise/partenaire", max_length=255, null=True, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='publicite',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('active', 'Active'), ('expiree', 'Expirée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='publicite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(blank=True, help_text="Définie par l'admin après confirmation du paiement", null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, help_text='Calculée automatiquement à partir de date_debut + durée offre', null=True, verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('montant_paye', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Montant payé (CFA)')),
                ('reference_paiement', models.CharField(blank=True, help_text='Référence ou note sur le paiement', max_length=100, null=True, verbose_name='Référence paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de souscription')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publicite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='core.publicite', verbose_name='Publicité')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='core.offreabonnement', verbose_name='Offre choisie')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
    ]
