# Generated by Django 5.2.1 on 2026-01-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactinfo_offreabonnement_servicemarketplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(db_index=True, help_text="Identifiant unique Firebase de l'utilisateur", max_length=128, unique=True, verbose_name='Firebase UID')),
                ('phone_number', models.CharField(db_index=True, help_text='Numéro de téléphone au format international (ex. +237699999999)', max_length=20, unique=True, verbose_name='Numéro de téléphone')),
                ('display_name', models.CharField(blank=True, help_text="Nom d'affichage optionnel de l'utilisateur", max_length=100, null=True, verbose_name="Nom d'affichage")),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour désactiver cet utilisateur', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
            ],
            options={
                'verbose_name': 'Utilisateur Mobile',
                'verbose_name_plural': 'Utilisateurs Mobiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
