# Generated by Django 5.2.1 on 2026-01-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_mobile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileuser',
            name='auth_method',
            field=models.CharField(choices=[('phone_sms', 'Téléphone SMS'), ('phone_password', 'Téléphone + Mot de passe'), ('google', 'Google OAuth')], default='phone_sms', help_text="Méthode d'authentification utilisée (phone_sms, phone_password, google)", max_length=20, verbose_name="Méthode d'auth"),
        ),
        migrations.AddField(
            model_name='mobileuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text="Email de l'utilisateur (pour Google Auth)", max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='mobileuser',
            name='photo_url',
            field=models.URLField(blank=True, help_text='URL de la photo de profil (Google)', null=True, verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='mobileuser',
            name='display_name',
            field=models.CharField(blank=True, help_text="Nom d'affichage de l'utilisateur", max_length=100, null=True, verbose_name="Nom d'affichage"),
        ),
        migrations.AlterField(
            model_name='mobileuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='Numéro de téléphone au format international (ex. +237699999999)', max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
