# Generated by Django 5.2.1 on 2026-01-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_mobileuser_auth_method_mobileuser_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_taxi_jour', models.PositiveIntegerField(default=300, help_text='Tarif standard pour un trajet en taxi partagé de jour (6h-18h)', verbose_name='Tarif taxi jour (FCFA)')),
                ('tarif_taxi_nuit', models.PositiveIntegerField(default=350, help_text='Tarif standard pour un trajet en taxi partagé de nuit (18h-6h)', verbose_name='Tarif taxi nuit (FCFA)')),
                ('tarif_course_jour', models.PositiveIntegerField(default=3500, help_text='Tarif pour une course/dépôt de jour (taxi privatisé, 6h-18h)', verbose_name='Tarif course jour (FCFA)')),
                ('tarif_course_nuit', models.PositiveIntegerField(default=4000, help_text='Tarif pour une course/dépôt de nuit (taxi privatisé, 18h-6h)', verbose_name='Tarif course nuit (FCFA)')),
                ('derniere_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('source', models.CharField(default='Ministère des Transports du Cameroun', help_text='Source officielle de ces tarifs (ex: Ministère des Transports)', max_length=255, verbose_name='Source officielle')),
                ('notes', models.TextField(blank=True, help_text="Notes ou commentaires sur les tarifs (ex: date d'entrée en vigueur)", null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Tarif Standard',
                'verbose_name_plural': 'Tarifs Standards',
            },
        ),
    ]
