# Generated by Django 5.2.1 on 2026-01-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tarifstandard'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_seuil_km', models.FloatField(default=15.0, help_text="Au-delà de cette distance, l'estimation utilise une régression linéaire au lieu du ML/proximité. Valeur recommandée : 15-20 km (largeur d'une grande ville).", verbose_name='Distance seuil (km)')),
                ('prix_par_km', models.PositiveIntegerField(default=150, help_text='Prix en FCFA par kilomètre pour les trajets dépassant le seuil. Utilisé dans la formule : prix = distance_km × prix_par_km', verbose_name='Prix par km (FCFA)')),
                ('prix_minimum_lineaire', models.PositiveIntegerField(default=500, help_text='Prix minimum garanti pour les trajets calculés en régression linéaire.', verbose_name='Prix minimum linéaire (FCFA)')),
                ('derniere_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('notes', models.TextField(blank=True, help_text='Notes ou justifications des valeurs choisies.', null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Configuration Estimation',
                'verbose_name_plural': 'Configuration Estimation',
            },
        ),
    ]
