"""
Django settings for fare_calculator project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Charger le .env immédiatement pour que les variables soient disponibles
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jd8m!=^lc83ov2q@l91kaj2b))lhv)$4mr@577e(yt*7-(q+**'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["fare-calculator-service.pynfi.com", "localhost", "127.0.0.1"]

# Configuration de sécurité pour le déploiement (Vercel + Pynfi)
CSRF_TRUSTED_ORIGINS = [
    "https://fare-calculator-service.pynfi.com",
    "https://fare-calculator-front.vercel.app"
]

# Détection du HTTPS derrière le reverse proxy (déploiement Docker/Pynfi)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ApiKeyMiddleware',  
]

ROOT_URLCONF = 'fare_calculator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fare_calculator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Si POSTGRES_DB est défini dans l'environnement, basculer sur PostgreSQL
if os.getenv('POSTGRES_DB'):
    # En dev local (Windows) avec Postgres installé en natif, 'db' ne fonctionnera pas.
    # On force 'localhost' si on détecte Windows ET que l'hôte indiqué est 'db'.
    db_host = os.getenv('POSTGRES_HOST', 'localhost')
    if os.name == 'nt' and db_host == 'db':
        db_host = 'localhost'

    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER', 'fox'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
        'HOST': db_host,
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }

# Redis Cache / Local Memory Cache
# En dev local sans Redis, on utilise LocMemCache pour éviter les erreurs de connexion.
# En prod (Docker), on utilisera Redis via variable d'env.
if os.getenv('REDIS_URL'):
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.getenv('REDIS_URL'),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Fare Calculator API',
    'DESCRIPTION': 'API REST pour estimation prix taxi au Cameroun',
    'VERSION': '2.0.0',
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'CONTACT': {'email': 'donfackarthur750@gmail.com'},
}
# REST Framework Pagination

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from decouple import config

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Douala'  # Pour Cameroun

# ==============================================================================
# CONFIGURATION APIs EXTERNES
# ==============================================================================

# Mapbox API Configuration
MAPBOX_ACCESS_TOKEN = os.getenv('MAPBOX_TOKEN', 'pk.eyJ1IjoibTJnaSIsImEiOiJjbWhramlqcnIwYW5rMmlzY3ViZmg1NGFmIn0.q3XQxQTte7ADbn32fwFh-g')
MAPBOX_BASE_URL = os.getenv('MAPBOX_BASE_URL', 'https://api.mapbox.com')
MAPBOX_CACHE_ENABLED = os.getenv('MAPBOX_CACHE_ENABLED', 'True').lower() == 'true'
MAPBOX_CACHE_TTL_SECONDS = int(os.getenv('MAPBOX_CACHE_TTL_SECONDS', '3600'))  # 1h pour données trafic dynamiques

# OpenMeteo API Configuration (gratuit, pas de token)
OPENMETEO_BASE_URL = os.getenv('OPENMETEO_BASE_URL', 'https://api.open-meteo.com/v1')

# Nominatim (OpenStreetMap) Configuration
NOMINATIM_BASE_URL = os.getenv('NOMINATIM_BASE_URL', 'https://nominatim.openstreetmap.org')
NOMINATIM_USER_AGENT = os.getenv('NOMINATIM_USER_AGENT', 'taxi-estimator-cameroun/1.0 (contact@example.com)')

# ==============================================================================
# CONSTANTES PROJET (TARIFS & SEUILS)
# ==============================================================================

# Prix standards Cameroun (tarifs officiels approximatifs)
PRIX_STANDARD_JOUR_CFA = float(os.getenv('PRIX_STANDARD_JOUR_CFA', '300'))  # Tarif jour de base
PRIX_STANDARD_NUIT_CFA = float(os.getenv('PRIX_STANDARD_NUIT_CFA', '350'))  # Tarif nuit (22h-6h), majoration +17%

# Classes de prix taxis Cameroun (pour ML classification - 18 classes)
# Les prix taxis ne sont PAS continus mais appartiennent à des tranches fixes
# Variation minimale : 50 CFA
PRIX_CLASSES_CFA = [
    100, 150, 200, 250, 300, 350, 400, 450, 500, 
    600, 700, 800, 900, 1000, 1200, 1500, 1700, 2000
]

# Seuils similarité trajets
MAX_DISTANCE_SIMILARITY_METERS = float(os.getenv('MAX_DISTANCE_SIMILARITY_METERS', '500'))  # Rayon cercle fallback si isochrones échouent
ISOCHRONE_MINUTES_EXACT = [int(os.getenv('ISOCHRONE_MINUTES_EXACT', '3'))]  # Périmètre exact (3 min = ~1km urbain)
ISOCHRONE_MINUTES_SIMILAR = [int(os.getenv('ISOCHRONE_MINUTES_SIMILAR', '7'))]  # Périmètre élargi (7 min = ~2-3km urbain)

# Ajustements prix
PRIX_AJUSTEMENT_PAR_100M = float(os.getenv('PRIX_AJUSTEMENT_PAR_100M', '15'))  # +15 CFA par 100m distance extra
PRIX_AJUSTEMENT_CONGESTION_POURCENT = float(os.getenv('PRIX_AJUSTEMENT_CONGESTION_POURCENT', '10'))  # +10% si congestion haute (>70)
PRIX_AJUSTEMENT_METEO_PLUIE_POURCENT = float(os.getenv('PRIX_AJUSTEMENT_METEO_PLUIE_POURCENT', '5'))  # +5% si pluie
PRIX_AJUSTEMENT_NUIT_POURCENT = float(os.getenv('PRIX_AJUSTEMENT_NUIT_POURCENT', '17'))  # +17% tarif nuit

# Seuils ML (minimum trajets requis pour entraînement)
MIN_TRAJETS_FOR_ML_TRAINING = int(os.getenv('MIN_TRAJETS_FOR_ML_TRAINING', '50'))  # 50 trajets minimum pour entraîner modèle

# ==============================================================================
# LOGGING CONFIGURATION
# ==============================================================================

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {module} {funcName}: {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': LOG_DIR / 'fare_calculator.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'core': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ---------------------------------------------------------------------------
# CORS (Cross-Origin Resource Sharing) - allow frontend preflight OPTIONS
# ---------------------------------------------------------------------------
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
    "https://fare-calculator-front.vercel.app",
    "https://fare-calculator-service.pynfi.com",
]

CORS_ALLOW_CREDENTIALS = True

# Ensure 'authorization' header is allowed in preflight and requests
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
